apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrIngress
metadata:
  name: "nublado-controller-admin"
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
config:
  baseUrl: {{ .Values.global.baseUrl | quote }}
  scopes:
    all:
      - "admin:jupyterlab"
template:
  metadata:
    name: "controller-admin"
  spec:
    rules:
      - host: {{ .Values.global.host | quote }}
        http:
          paths:
            - path: {{ .Values.controller.config.safir.pathPrefix | quote }}
              pathType: "Prefix"
              backend:
                service:
                  name: "nublado-controller"
                  port:
                    number: 80
