prompt-proto-service:

  podAnnotations:
    # Update this field if using latest or static image tag in dev
    revision: "1"

  image:
    repository: ghcr.io/lsst-dm/prompt-proto-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  instrument:
    pipelines: (survey="SURVEY")=[${PROMPT_PROTOTYPE_DIR}/pipelines/HSC/ApPipe.yaml]
    calibRepo: s3://rubin:rubin-pp-users/central_repo/

  s3:
    imageBucket: rubin:rubin-pp
    endpointUrl: https://s3dfrgw.slac.stanford.edu
    disableBucketValidation: '1'

  imageNotifications:
    kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
    topic: rubin-prompt-processing

  apdb:
    url: postgresql://rubin@usdf-prompt-processing-dev.slac.stanford.edu:5432/lsst-devl
    ip: usdf-prompt-processing-dev.slac.stanford.edu:5432  # TODO: remove on DM-40839

  registry:  # TODO: remove on DM-40839
    ip: usdf-prompt-processing-dev.slac.stanford.edu:5432
    db: ppcentralbutler
    user: pp

  fullnameOverride: "prompt-proto-service-hsc"
