name: "ukidacdev"
fqdn: "rsp-test.lsst.ac.uk"
appOfAppsName: "science-platform"
vaultUrl: "https://vault-rsp.lsst.ac.uk"
vaultPathPrefix: "secret/phalanx/ukidacdev"
applications:
  butler: true
  datalinker: true
  mobu: false
  nublado: true
  portal: true
  postgres: true
  qserv-kafka: true
  sasquatch: true
  semaphore: true
  squareone: true
  strimzi: true
  strimzi-access-operator: true
  strimzi-registry-operator: true
  tap: true
