config:
  logLevel: "DEBUG"
  qservDatabaseUrl: "mysql+asyncmy://qsmaster@192.41.122.106:30431"
  qservRestSendApiVersion: false
  qservRestUrl: "https://192.41.122.106:30081"
frontend:
  allowRootDebug: true
resultWorker:
  allowRootDebug: true
  autoscaling:
    maxReplicas: 50
