config:
  autostart:
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
      scopes: ["read:tap"]
      business:
        type: "TAPQuerySetRunner"
        options:
          queries: 
            - "SELECT TOP 10 * FROM TAP_SCHEMA.tables"
            - "SELECT TOP 10 * FROM  video.hsc_g_f"
        restart: true
