# config:
#   sentryTracesSampleConfig: errors
#   autostart:
#     - name: "firefighter"
#       count: 1
#       users:
#         - username: "bot-mobu04"
#           uidnumber: 45695
#           gidnumber: 1126
#       scopes:
#         - "exec:notebook"
#         - "exec:portal"
#         - "read:image"
#         - "read:tap"
#       business:
#         type: "NotebookRunner"
#         options:
#           repo_url: "https://github.com/lsst-sqre/system-test.git"
#           repo_ref: "prod"
#         restart: true
#     - name: "tap"
#       count: 1
#       users:
#         - username: "bot-mobu05"
#           uidnumber: 45696
#           gidnumber: 1126
#       scopes: ["read:tap"]
#       business:
#         type: "TAPQuerySetRunner"
#         options:
#           query_set: "dp0.2"
#         restart: true
config:
  autostart:
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-recommended"
          uidnumber: 74768
          gidnumber: 74768
      scopes: ["read:tap"]
      business:
        type: "TAPQueryRunner"
        options:
          queries:
            - "SELECT TOP 10 * FROM  video.hsc_g_f"
            - "SELECT TOP 10 * FROM  TAP_SCHEMA.tables"
            - "SELECT TOP 10 * FROM  viking.hsc_g_f"
        restart: true
    - name: "notebooks"
      count: 1
      users:
        - username: "bot-mobu-weekly"
          uidnumber: 74769
          gidnumber: 74769
      scopes: ["exec:notebook", "exec:portal", "read:image", "read:tap"]
      business:
        type: "NotebookRunner"
        options:
          image:
            image_class: "latest-weekly"
          repo_url: "https://github.com/lsst-uk/rsp-uk-notebooks.git"
          repo_ref: "mobu"
        restart: true
