---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: butler-secret
  labels:
    {{- include "obsloctap.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/butler-secret"
  type: Opaque
