controller:
  config:
    images:
      source:
        type: "docker"
        registry: "registry.hub.docker.com"
        repository: "lsstsqre/sciplat-lab"
    lab:
      env:
        AUTO_REPO_BRANCH: "main"
        AUTO_REPO_SPECS: "https://github.com/lsst-uk/unified-tutorial-notebooks@main"
        AUTO_REPO_URLS: "https://github.com/lsst-uk/unified-tutorial-notebooks"
        RSP_SITE_TYPE: "science"
        TUTORIAL_NOTEBOOKS_URL: "https://github.com/lsst-uk/unified-tutorial-notebooks@main"
        DAF_BUTLER_REPOSITORY_INDEX: "/data/butler/data-repos.yaml"
      pullSecret: "pull-secret"
      standardInithome: true
      volumes:
        - name: "data"
          source:
            serverPath: "/data"
            server: "192.41.122.33"
            type: "nfs"
        - name: "home"
          source:
            serverPath: "/jhome"
            server: "192.41.122.33"
            type: "nfs"
        - name: "datasets"
          source:
            serverPath: "/datasets"
            server: "192.41.122.33"
            type: "nfs"
        # - name: "rubin"
        #   source:
        #     serverPath: "/data/butler/rubin"
        #     server: "192.41.122.33"
        #     type: "nfs"
        - name: "lsdb-dp1"
          source:
            serverPath: "/data/butler/rubin/lsdb_data/dp1"
            server: "192.41.122.33"
            type: "nfs"
        - name: "cst-repos"
          source:
            serverPath: "/data/butler/rubin/cst_repos"
            server: "192.41.122.33"
            type: "nfs"
        - name: "rubin-sim-data"
          source:
            serverPath: "/data/butler/rubin/rubin_sim_data"
            server: "192.41.122.33"
            type: "nfs"
      volumeMounts:
        - containerPath: "/data"
          volumeName: "data"
        - containerPath: "/home"
          volumeName: "home"
        - containerPath: "/datasets"
          volumeName: "datasets"
        #- containerPath: "/rubin"
       #   volumeName: "rubin"
       # Change back when tutorial paths are updated
        - containerPath: "/rubin/lsdb_data"
          volumeName: "lsdb-dp1"
        - containerPath: "/rubin/cst_repos"
          volumeName: "cst-repos"
        - containerPath: "/rubin/rubin_sim_data"
          volumeName: "rubin-sim-data"

proxy:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "50s"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "50s"
      nginx.ingress.kubernetes.io/client-max-body-size: "50m"

hub:
  internalDatabase: true

jupyterhub:
  hub:
    db:
      upgrade: true

secrets:
  templateSecrets: false
