apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: restart-test-workflow
  labels:
    workflows.argoproj.io/type: "integration-test"
    argocd.argoproj.io/instance: integration-testing
spec:
  serviceAccountName: {{ .Values.serviceAccount }}
  artifactRepositoryRef:
    configMap: integration-test-controller-configmap
    key: artifactRepository
  volumes:
  - name: testreports
    persistentVolumeClaim:
      claimName: {{ .Values.persistentVolume.claimName }}
  podMetadata:
    labels:
      argocd.argoproj.io/instance: integration-testing
  arguments:
    parameters:
    - name: date-key
      value: "20230601"
  entrypoint: run-tests
  onExit: save-reports
  templates:
  - name: run-tests
    dag:
      tasks:
      - name: cameras-offline
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_Offline.list"
          - name: jobname
            value: cameras-offline
      - name: standby
        depends: cameras-offline
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_Standby.list"
          - name: jobname
            value: standby
      - name: disabled
        depends: standby
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_Disabled.list"
          - name: jobname
            value: disabled
      - name: enabled
        depends: disabled
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_Enabled.list"
          - name: jobname
            value: enabled
      - name: auxtel-housekeeping
        depends: enabled
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_AuxTel_Housekeeping.list"
          - name: jobname
            value: auxtel-housekeeping
      - name: maintel-housekeeping
        depends: enabled
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_MainTel_Housekeeping.list"
          - name: jobname
            value: maintel-housekeeping
      - name: auxtel-image-verification
        depends: auxtel-housekeeping
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_AuxTel_Image_Verification.list"
          - name: jobname
            value: auxtel-image-verification
      - name: comcam-image-verification
        depends: maintel-housekeeping
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_BigCamera_Image_Verification.list"
          - name: jobname
            value: comcam-image-verification
      - name: love-stress-test
        depends: auxtel-image-verification && comcam-image-verification
        templateRef:
          name: integration-test-job-template
          template: inttest-template
        arguments:
          parameters:
          - name: integrationtest
            value: "-A Test_Report_LOVE_Stress_Test.list"
          - name: jobname
            value: love-stress-test

  - name: save-reports
    container:
      image: alpine:latest
      volumeMounts:
        - name: testreports
          mountPath: {{ .Values.reportLocation }}
    outputs:
      artifacts:
      - name: integration-test-reports
        archive:
          none: {}
        path: {{ .Values.reportLocation }}/
        s3:
          key: IntegrationTests/{{ printf "{{workflow.parameters.date-key}}" }}
