config:
  datasets:
    macauff_gaiadr3xcatwise:
      description: >-
        Table of counterpart associations between Gaia DR3 and CatWISE2020.
        Uses probabilistic cross-match algorithms as described by Wilson
        &amp; Naylor (MNRAS, 2017, 2018a,b) and Wilson (RNAAS, 2022).
        Sources are returned either as a pairing, in which the Gaia and
        WISE objects are the same astrophysical source detected twice, or
        as non-matches, with that particular object in one of the catalogues
        having a corresponding flux upper limits in the opposing catalogue,
        and entries include various pieces of metadata such as the
        probability of the match/non-match, likelihood of match on purely
        position or brightness grounds, and information on the level to
        which objects suffer contamination due to hidden and unresolved
        background sources.
        docsUrl: "https://dp1.lsst.io/"
    comcam_vista:
      description: >-
        This dataset is produced with the LSST–VISTA Fusion Pipeline for the DP1 ComCam–VISTA data in
        the Extended Chandra Deep Field South (ECDFS). The pipeline processes VISTA near-infrared
        imaging within an LSST-style framework and combines it with ComCam optical data in a common
        Butler environment for joint analysis.
        The main products are pixel-matched Coadd images and associated catalogue products across the
        available optical and near-infrared bands. These fused products enable consistent photometric analysis
        across wavelengths, making them particularly well suited for colour studies, SED-based analysis, and
        any science that benefits from uniform measurements over all bands.
        docsUrl: "https://community.lsst.org/t/lsst-dp1-vista-video-fusion-dataset-on-the-uk-rsp/12189"
  availableDatasets:
    - "dp1"
    - "dp2"
    - "macauff_gaiadr3xcatwise"
    - "macauff_gaiadr3x2mass"
    - "ivoa_obscore"
    - "comcam_vista"
  tap:
    schemaVersion: "w.2026.29-dev.09d31e2"
    schemaSourceTemplate: "https://github.com/lsst-uk/sdm_schemas/archive/refs/tags/w.2026.29-dev.09d31e2.tar.gz"
    servers:
      tap:
        schemas:
          - dp1
          - dp2
          - macauff_gaiadr3xcatwise
          - macauff_gaiadr3x2mass
          - ivoa_obscore
        enabled: true
        databaseUrl: "postgresql://tap@192.41.122.236:5432/tap"
        databasePasswordKey: "tap-database-password"
      ssotap:
        enabled: false
