config:
  availableDatasets:
    - "dp1"
  tap:
    servers:
      tap:
        enabled: true
        databaseUrl: "postgresql://tap@10.72.0.77:5432/tap"
        databasePasswordKey: "tap-database-password"
      ssotap:
        enabled: false
