replicaCount: 2

redis:
  persistence:
    enabled: true
    size: "32Gi"
    storageClass: "cephfs"
  resources:
    limits:
      memory: "1Gi"

resources:
  limits:
    cpu: "4"
    memory: "60Gi"
  requests:
    cpu: "1"
    memory: "16Gi"
