replicaCount: 2
config:
  cleanupInterval: "1h"
  volumes:
    sharedWorkarea:
      nfs:
        path: "/portal/sharedWorkarea"
        server: "192.41.122.33"
    privateWorkarea:
      pvc:
        size: "5Gi"
        storageClass: "standard-rwo"
