cadc-tap:
  tapSchema:
    type: "external"
    database: "tap"
    username: "tap"
    useVaultPassword: true
    external:
      host: 192.41.122.236
      port: 5432

  uws:
    type: "external"
    database: "tap"
    username: "tap"
    useVaultPassword: true
    external:
      host: 192.41.122.236
      port: 5432

  config:
    gcsBucket: "async-test"
    gcsBucketUrl: "https://somerville.ed.ac.uk:6780"
    gcsBucketType: "S3"

    urlRewrite:
      enabled: true
      rules: "ivoa.ObsCore:access_url, dp02_dc2_catalogs.ObsCore:access_url, dp1.ObsCore:access_url"

    qserv:
      host: "192.41.122.106:30431"
      jdbcParams: "?enabledTLSProtocols=TLSv1.3"
      passwordEnabled: true
      image:
        tag: "3.25.0"

    kafka:
      enabled: true
